'use client';
import {useEffect,useRef,useState,useCallback,useMemo} from 'react';
import {BookOpen,NotebookPen,ChartNoAxesCombined,Check,CheckCheck,ChevronRight,ChevronLeft,ArrowRight,RotateCcw,Languages,Clock3,CloudCheck,HardDrive,Target,GraduationCap,TriangleAlert,ExternalLink,XCircle,Layers3,Loader2,Flag,History,Brain,Plus,LibraryBig} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AnswerReview} from './answer-review';
import {TextbookReader} from './textbook-reader';
import {linkedTextbooks} from '@/lib/textbooks';
import {QuestionLibrary} from './question-library';
import {subjectById,subjects} from '@/lib/subjects';
import {chapterById,chapters} from '@/lib/chapters';
import {explainLegalText} from '@/lib/review-language';
import {sourceById,questionNumberLabel} from '@/lib/question-sources';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Progress} from '@/components/ui/progress';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import type {Question,StudyData,Session} from '@/lib/study-types';
import {examDurationMs} from '@/lib/study-timing';
import {Toaster} from '@/components/ui/sonner';
import {useVocabulary,VocabularyPanel,VocabularyEditor,VocabularySelection,VocabularySource,newWordDraft,cardDraft} from './vocabulary-panel';
import {dueCards} from '@/lib/vocabulary';
import type {VocabularyDraft} from '@/lib/vocabulary';
import {TextbookLibrary} from './textbook-library';
import {useTextbookAnnotations} from './use-textbook-annotations';
import {useTextbookCatalog} from './use-textbook-catalog';
import {normalizeInlineQuestionText} from '@/lib/question-text';
import {applyGuestStudyAction} from '@/lib/guest-study';
const modeName=(m:string)=>m==='exam'?'限时模拟':m==='wrong'?'错题重练':'刷题练习';
function Nav({view,setView,due,guest}:{view:string;setView:(v:string)=>void;due:number;guest:boolean}){const {setOpenMobile}=useSidebar();return <Sidebar collapsible="offcanvas"><SidebarHeader className="p-0"><div className="brand"><div className="brand-mark">S</div><div><strong>SQE Practice</strong><small>个人刷题室</small></div></div></SidebarHeader><SidebarContent className="sidebar-menu-content"><div className="side-label">MY WORKSPACE</div><SidebarMenu className="side-nav">{[{id:'library',label:'题库分类',icon:Layers3},{id:'practice',label:'刷题练习',icon:BookOpen},{id:'materials',label:'教材笔记',icon:LibraryBig},{id:'wrong',label:'错题本',icon:NotebookPen},{id:'memory',label:'艾宾浩斯记忆',icon:Brain},{id:'history',label:'学习记录',icon:ChartNoAxesCombined}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{setView(n.id);setOpenMobile(false);}}><n.icon/><span>{n.label}</span>{n.id==='memory'&&due>0&&<span className="ml-auto text-xs rounded bg-[#40577d] px-2 py-0.5">{due}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-0"><div className="side-footer"><div className="avatar">{guest?<HardDrive size={18}/>:<GraduationCap size={19}/>}</div><div className="text-sm">{guest?'访客学习空间':'我的学习空间'}<small>{guest?'当前浏览器 · 自动保存':'个人记录 · 云端同步'}</small></div></div></SidebarFooter></Sidebar>}
const accuracyText=(value:number|null)=>value==null?'—':`${value}%`;
function StudyBreakdown({data}:{data:StudyData}){
 const bySubject=new Map(data.stats.subjects.map(item=>[item.subjectId,item]));
 const answeredSubjects=data.stats.subjects.filter(item=>item.answered>0).length;
 return <section className="history-breakdown" aria-labelledby="history-breakdown-title"><div className="history-breakdown-head"><div><div className="eyebrow">SUBJECT PERFORMANCE</div><h2 id="history-breakdown-title">科目与章节统计</h2><p>按题目的主章节归类；展开科目可查看各章节表现。</p></div><span>{answeredSubjects}/{subjects.length} 个科目已有记录</span></div><div className="subject-stat-list">{subjects.map(subject=>{const stat=bySubject.get(subject.id);const answered=stat?.answered??0;const correct=stat?.correct??0;const accuracy=stat?.accuracy??null;const subjectChapters=chapters.filter(chapter=>chapter.subjectId===subject.id);const byChapter=new Map(stat?.chapters.map(item=>[item.chapterId,item])??[]);const uncategorized=byChapter.get(null);return <details className="subject-stat-card" key={subject.id}><summary><div className="subject-stat-title"><span>{subject.group}</span><div><strong>{subject.zh}</strong><small>{subject.en}</small></div></div><div className="subject-stat-meter"><Progress value={accuracy??0} aria-label={`${subject.zh}正确率`} className="h-1.5 bg-[#e7ebf3]"/><small>{correct}/{answered} 题答对</small></div><div className="subject-stat-value"><strong>{answered}</strong><small>答题数量</small></div><div className="subject-stat-value accuracy"><strong>{accuracyText(accuracy)}</strong><small>正确率</small></div><ChevronRight className="subject-stat-chevron" size={18}/></summary><div className="chapter-stat-wrap">{subjectChapters.length||uncategorized?<table className="chapter-stat-table"><thead><tr><th>章节</th><th>答题数量</th><th>正确率</th></tr></thead><tbody>{subjectChapters.map(chapter=>{const chapterStat=byChapter.get(chapter.id);return <tr key={chapter.id}><td><b>第 {chapter.number} 章</b><span>{chapter.zh}</span></td><td>{chapterStat?.answered??0}</td><td><strong>{accuracyText(chapterStat?.accuracy??null)}</strong><small>{chapterStat?.answered?`${chapterStat.correct}/${chapterStat.answered} 题答对`:'暂无作答'}</small></td></tr>;})}{uncategorized&&<tr><td><b>其他</b><span>尚未匹配主章节的题目</span></td><td>{uncategorized.answered}</td><td><strong>{accuracyText(uncategorized.accuracy)}</strong><small>{uncategorized.correct}/{uncategorized.answered} 题答对</small></td></tr>}</tbody></table>:<p className="chapter-stat-empty">该科目暂无章节目录。</p>}</div></details>;})}</div></section>;
}
const GUEST_STUDY_KEY='sqe-practice:guest-study:v1';
function readGuestStudy(){try{return JSON.parse(localStorage.getItem(GUEST_STUDY_KEY)??'null');}catch{return null;}}
function saveGuestStudy(state:unknown){try{localStorage.setItem(GUEST_STUDY_KEY,JSON.stringify(state));}catch{throw new Error('浏览器无法保存学习进度，请检查是否允许本站使用本机存储。');}}
function StudyContent({authenticated,standalone}:{authenticated:boolean;standalone:boolean}){
 const guest=standalone||!authenticated;
 const vocabulary=useVocabulary(guest);
 const annotations=useTextbookAnnotations(guest);
 const textbookCatalog=useTextbookCatalog(guest);
 const[wordDraft,setWordDraft]=useState<VocabularyDraft|null>(null),[sourceQuestion,setSourceQuestion]=useState<Question|null>(null);
 const studyTextRef=useRef<HTMLDivElement|null>(null);

 const[data,setData]=useState<StudyData|null>(null);const[view,setView]=useState('library');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[needsLogin,setNeedsLogin]=useState(false);const[selected,setSelected]=useState('');const[showZh,setShowZh]=useState(false);const[dialog,setDialog]=useState<'exam'|'practice'|'finish'|null>(null);const[summary,setSummary]=useState(false);const[now,setNow]=useState(Date.now());const[showCorrected,setShowCorrected]=useState(false);const[localPosition,setLocalPosition]=useState(0);
 const[reader,setReader]=useState<{questionId:string;bookId:string;page:number}|null>(null);
 const busyRef=useRef(false);const dataRef=useRef(data);dataRef.current=data;const selectedRef=useRef(selected);selectedRef.current=selected;const opRef=useRef<(body:Record<string,unknown>)=>Promise<StudyData|undefined>>(null);const expiryTried=useRef('');const webActions=useRef<Record<string,(x:any)=>any>>({});
 const session=data?.session;const ids=session?.questionIds??data?.questions.filter(q=>q.sourceId==='sra').map(q=>q.id)??[];const position=session?.position??localPosition;const q=data?.questions.find(q=>q.id===ids[position]);const answer=q?session?.answers[q.id]:undefined;const graded=!!answer&&(session?.mode!=='exam'||session.status==='finished');const activeExam=session?.mode==='exam'&&session.status==='active';const completed=ids.filter(id=>session?.answers[id]?.selected).length;
 const displayStem=normalizeInlineQuestionText(q?.stem??'');
 const displayAsk=normalizeInlineQuestionText(q?.ask??'');
 const displayOptions=useMemo(()=>q?.options.map(option=>normalizeInlineQuestionText(option.en))??[],[q]);
 const visibleStemZh=normalizeInlineQuestionText(q?.stemZh||'');
 const visibleAskZh=normalizeInlineQuestionText(q?.askZh||'');
 const visibleOptionZh=(index:number)=>normalizeInlineQuestionText(q?.options[index]?.zh||'');
 const hasQuestionTranslation=!!visibleStemZh||!!visibleAskZh||!!q?.options.some(option=>option.zh?.trim());
 const readerOpen=!!reader&&reader.questionId===q?.id&&graded&&!activeExam;
 useEffect(()=>{window.scrollTo({top:0});setReader(null);},[view,q?.id,session?.id,summary]);
 const remaining=activeExam?Math.max(0,Math.ceil((session.startedAt+examDurationMs(ids)-now)/1000)):0;
 const adopt=useCallback((d:StudyData)=>{setData(d);const id=d.session?.questionIds[d.session.position]??d.questions.filter(q=>q.sourceId==='sra')[localPosition]?.id;setSelected(id?d.session?.answers[id]?.selected??'':'');},[localPosition]);
 async function request(body?:Record<string,unknown>,sessionId?:string){
  if(guest){
   const action={...body,action:body?.action??'hydrate',sessionId:body?.sessionId??sessionId};
   if(standalone){const value=applyGuestStudyAction(readGuestStudy(),action);saveGuestStudy(value.state);setNeedsLogin(false);return value.data;}
   const response=await fetch('/api/guest-study',{method:'POST',headers:{'Content-Type':'application/json','X-Study-Action':'1'},body:JSON.stringify({...action,state:readGuestStudy()})});const value=await response.json() as {data?:StudyData;state?:unknown;error?:string};if(!response.ok||!value.data)throw new Error(value.error??'暂时无法读取本机进度，请重试。');saveGuestStudy(value.state);setNeedsLogin(false);return value.data;
  }
  const response=await fetch('/api/study'+(sessionId?'?session='+encodeURIComponent(sessionId):''),body?{method:'POST',headers:{'Content-Type':'application/json','X-Study-Action':'1'},body:JSON.stringify(body)}:{cache:'no-store'});const value=await response.json() as StudyData & {error?:string};if(!response.ok){if(response.status===401)setNeedsLogin(true);throw new Error(value.error??'暂时无法连接，请重试。');}setNeedsLogin(false);return value as StudyData;
 }
 const load=useCallback(async()=>{setLoading(true);setError('');try{const d=await request();setData(d);const id=d.session?.questionIds[d.session.position];setSelected(id?d.session?.answers[id]?.selected??'':'');}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
 useEffect(()=>{void load();},[load]);
 const mutate=useCallback(async(body:Record<string,unknown>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{const d=await request(body);adopt(d);return d;}catch(e){setError((e as Error).message);return undefined;}finally{busyRef.current=false;setBusy(false);}},[adopt]);opRef.current=mutate;
 useEffect(()=>{if(!activeExam)return;const t=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(t);},[activeExam]);
 useEffect(()=>{if(activeExam&&remaining===0&&!busy&&expiryTried.current!==session.id){expiryTried.current=session.id;void mutate({action:'finish',sessionId:session.id}).then(d=>{if(d){setDialog(null);setSummary(true);}else expiryTried.current='';});}},[remaining,activeExam,busy,session?.id,mutate]);
 async function start(mode:'practice'|'exam'|'wrong',questionId?:string,subjectId?:string,sourceId?:string,chapterId?:string,sourceSet?:string){const d=await mutate({action:'start',id:crypto.randomUUID(),mode,questionId,subjectId,chapterId,sourceSet:sourceSet??(mode!=='wrong'&&sourceId===undefined&&subjectId===undefined&&chapterId===undefined?activeSourceSet:undefined),sourceId:sourceId==='all'?undefined:sourceId??(mode==='wrong'?undefined:q?.sourceId??'sra')});if(d){setView('practice');setSummary(false);setDialog(null);setShowZh(false);setNow(Date.now());expiryTried.current='';}return d;}
 async function navigate(next:number){if(next<0||next>=ids.length||busyRef.current)return false;if(session){const d=await mutate({action:'navigate',sessionId:session.id,position:next});if(!d)return false;}else{setLocalPosition(next);setSelected('');}setShowZh(false);setSummary(false);return true;}
 async function submit(){if(!q||!selected||busyRef.current||graded)return;let s=session;const choice=selected;if(!s){const d=await start('practice');if(!d?.session)return;s=d.session;if(position!==0){const moved=await mutate({action:'navigate',sessionId:s.id,position});if(!moved)return;}}const d=await mutate({action:'answer',sessionId:s.id,questionId:q.id,selected:choice});if(d){if(d.session?.mode==='exam'&&d.session.status==='finished')setSummary(true);}}
 async function choose(value:string){if(busyRef.current||graded)return;setSelected(value);if(activeExam&&q){const d=await mutate({action:'answer',sessionId:session.id,questionId:q.id,selected:value});if(d?.session?.status==='finished')setSummary(true);}}
 async function finishSession(){if(!session)return;const d=await mutate({action:'finish',sessionId:session.id});if(d){setDialog(null);setSummary(true);}}
 function toggleQuestionLanguage(){setShowZh(value=>!value);}
 async function openSession(s:Session){if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{const d=await request(undefined,s.id);adopt(d);setView('practice');setSummary(d.session?.status==='finished');setShowZh(false);}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const unsavedExam=activeExam&&selected!==(answer?.selected??'');
 webActions.current={read:()=>({view,mode:session?.mode??'practice',question:q?{id:q.id,number:q.number,stem:q.stem,ask:q.ask,options:q.options}:null,selected,submitted:graded,stats:data?.stats}),navigate:async(input:unknown)=>{const n=(input as {questionNumber?:number})?.questionNumber;if(!Number.isInteger(n)||!n||n<1||n>ids.length)throw Error('Invalid questionNumber');if(unsavedExam)throw Error('Save the pending exam answer first');const index=n-1;if(!await navigate(index))throw Error('Unable to navigate');return{questionNumber:n};}};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const registrations=[{name:'read_current_sqe_question',description:'Read the visible practice question, staged selection and study statistics without showing an unsubmitted answer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(input&&Object.keys(input as object).length)throw Error('No arguments accepted');return webActions.current.read(input);}},{name:'navigate_to_sqe_question',description:'Navigate to a numbered question in the current practice session and save its position. Does not submit an answer.',inputSchema:{type:'object',properties:{questionNumber:{type:'integer',minimum:1}},required:['questionNumber'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>webActions.current.navigate(input)}];for(const t of registrations){try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[]);
 const switchView=(v:string)=>{setView(v);setSummary(false);};
 const pending=data?.mistakes.filter(m=>!m.lastCorrect)??[];const mistakes=showCorrected?data?.mistakes??[]:pending;
 const currentSubject=subjectById(q?.subjectId);
 const activeSourceSet=q?.sourceSet&&session?.questionIds.every(id=>data?.questions.find(item=>item.id===id)?.sourceSet===q.sourceSet)?q.sourceSet:undefined;
 const examIds=(data?.questions??[]).filter(x=>x.sourceId===(q?.sourceId??'sra')&&(!activeSourceSet||x.sourceSet===activeSourceSet)).map(x=>x.id);
 const examMinutes=Math.ceil(examDurationMs(examIds)/60000);
 const focusedPractice=view==='practice'&&!summary;
 const syncBusy=busy||vocabulary.busy||annotations.busy||textbookCatalog.busy;const syncError=error||((view==='memory'||wordDraft)?vocabulary.error:'')||(view==='materials'?(annotations.error||textbookCatalog.error):'');const syncLoading=loading||(view==='memory'&&vocabulary.loading)||(view==='materials'&&(annotations.loading||textbookCatalog.loading));
 const title=view==='memory'?'艾宾浩斯记忆':view==='materials'?'教材笔记':view==='library'?'题库分类':view==='wrong'?'错题本':view==='history'?'学习记录':summary?'本次练习完成':session?.mode==='wrong'?'错题重练':activeExam?'限时模拟':'刷题练习';
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Nav view={view} setView={switchView} due={vocabulary.data?dueCards(vocabulary.data.cards,vocabulary.data.today).length:0} guest={guest}/><main className="min-w-0 flex-1"><header className="topbar"><div className="crumb"><SidebarTrigger className="md:hidden"/><span>学习空间</span><ChevronRight size={13}/><b>{title}</b>{focusedPractice&&q&&<div className="practice-context" aria-label="当前题目位置"><span className="tag">{currentSubject?.group??'SQE1'}</span><button className="tag subject-switch" onClick={()=>switchView('library')}>{currentSubject?.en??'切换科目'}<ChevronRight size={12}/></button><span className="demo-label">{sourceById(q.sourceId)?.name??'题目来源'} · {questionNumberLabel(q)}</span></div>}</div><div className="save-state">{syncBusy?<Loader2 size={15} className="animate-spin"/>:syncError?<TriangleAlert size={15}/>:guest?<HardDrive size={15}/>:<CloudCheck size={15}/>}<span>{syncBusy?'保存中…':syncLoading?'正在读取…':syncError?'保存待恢复':guest?'本机保存':'学习记录已同步'}</span>{guest&&!standalone&&<a href="/signin-with-chatgpt?return_to=%2F" target="_top">登录同步</a>}</div></header><div className={`workspace ${focusedPractice?'practice-workspace':''} ${view==='library'?'library-workspace':''} ${view==='memory'?'memory-workspace':''} ${view==='materials'?'textbook-library-workspace':''} ${readerOpen?'reading-workspace':''}`}>{!focusedPractice&&view!=='library'&&view!=='memory'&&view!=='materials'&&<><div className="page-heading"><div><div className="eyebrow">{view==='library'?'YOUR QUESTION LIBRARY':view==='practice'?'PRACTICE & UNDERSTAND':view==='wrong'?'REVISIT & REMEMBER':'YOUR LEARNING JOURNEY'}</div><h1>{title}</h1><p>{view==='library'?'按题目来源和科目选择练习题组。':view==='practice'?`${currentSubject?.en??'Practice'} · ${currentSubject?.zh??'综合练习'}`:view==='wrong'?'重做错题，直到能解释每一个选项。':'每一次作答，都留下进步的线索。'}</p></div></div>
 <div className="stat-strip"><div className="stat"><div className="stat-icon"><CheckCheck/></div><div><small>累计作答</small><strong>{data?.stats.answered??0}</strong><em>次</em></div></div><div className="stat"><div className="stat-icon"><Target/></div><div><small>累计正确率</small><strong>{data?.stats.accuracy==null?'—':`${data.stats.accuracy}%`}</strong></div></div><div className="stat"><div className="stat-icon"><NotebookPen/></div><div><small>待巩固错题</small><strong>{data?.stats.wrongCount??0}</strong><em>题</em></div></div></div></>}
 {error&&<div className="notice error" role="alert"><TriangleAlert size={18} className="shrink-0 mt-0.5"/><div className="flex-1">{error}{unsavedExam&&<p className="mt-1">当前选择尚未确认保存，请点击“重试保存”。</p>}</div>{needsLogin?<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="underline whitespace-nowrap">登录</a>:!data?<Button variant="outline" onClick={load}>重试</Button>:unsavedExam?<Button variant="outline" onClick={()=>choose(selected)}>重试保存</Button>:<Button variant="ghost" onClick={()=>setError('')}>关闭</Button>}</div>}
 {loading&&<div className="empty"><Loader2 size={27} className="animate-spin"/><h2>正在读取你的学习进度</h2><p>准备好后，就可以开始答题。</p></div>}
 {view==='memory'&&<VocabularyPanel controller={vocabulary} onAdd={()=>setWordDraft(newWordDraft())} onEdit={card=>setWordDraft(cardDraft(card))} onSource={id=>setSourceQuestion(data?.questions.find(q=>q.id===id)??null)} onPractice={()=>switchView('practice')} activeExam={!!activeExam}/>}
 {view==='materials'&&<TextbookLibrary controller={annotations} catalog={textbookCatalog} guest={guest}/>}
 {!loading&&view==='library'&&data&&<QuestionLibrary data={data} busy={busy} onStart={(id,sourceId,chapterId,sourceSet)=>void start('practice',undefined,id,sourceId,chapterId,sourceSet)} onResume={s=>void openSession(s)}/>}
 {!loading&&view==='practice'&&data&&q&&!summary&&<><div className={`study-grid ${readerOpen?'with-textbook':'practice-single'}`}><div className="study-main" ref={studyTextRef} onClickCapture={event=>{if((event.target as HTMLElement).closest('label.option')&&window.getSelection()?.toString().trim()){event.preventDefault();event.stopPropagation();}}}><article id="current-question" className="question-card"><div className="question-top"><h1 className="question-number"><span className="sr-only">第 </span><b>{String(position+1).padStart(2,'0')}</b><span className="sr-only"> 题</span> / {String(ids.length).padStart(2,'0')}</h1><div className="question-controls">{!activeExam&&<Button variant="ghost" size="sm" onClick={()=>setWordDraft(newWordDraft(q,session?.id))}><Plus size={15}/>记生词</Button>}<Tabs className="practice-mode" value={activeExam?'exam':'practice'} onValueChange={v=>{if(v==='exam'&&!activeExam)setDialog('exam');if(v==='practice'&&activeExam)setDialog('practice');}}><TabsList><TabsTrigger value="practice"><BookOpen size={15}/>学习模式</TabsTrigger><TabsTrigger value="exam"><Clock3 size={15}/>限时模拟</TabsTrigger></TabsList></Tabs>{activeExam?<div className="timer" aria-label="剩余时间"><Clock3 size={16}/><span>{Math.floor(remaining/60).toString().padStart(2,'0')}:{(remaining%60).toString().padStart(2,'0')}</span></div>:hasQuestionTranslation&&<Button variant="ghost" size="sm" aria-pressed={showZh} onClick={toggleQuestionLanguage}><Languages size={16}/> {showZh?'隐藏中文':'显示中文'}</Button>}</div></div><div className="question-body">{!activeExam&&q.chapterId&&<p className="question-chapter">第 {chapterById(q.chapterId)?.number} 章 · {chapterById(q.chapterId)?.zh}</p>}<p className="question-stem" lang="en">{displayStem}</p>{showZh&&!activeExam&&visibleStemZh&&<p className="zh-text stem-zh">{explainLegalText(visibleStemZh)}</p>}<p className="question-ask" lang="en">{displayAsk}</p>{showZh&&!activeExam&&visibleAskZh&&<p className="zh-text mb-4">{explainLegalText(visibleAskZh)}</p>}<RadioGroup aria-label="请选择一个最佳答案" value={selected} onValueChange={choose} disabled={graded||busy||session?.status==='finished'} className="options">{q.options.map((o,index)=><label key={o.id} htmlFor={`answer-${q.id}-${o.id}`} className={`option ${selected===o.id?'selected':''} ${graded&&q.explanation?.answer===o.id?'correct':''} ${graded&&answer.selected===o.id&&!answer.correct?'incorrect':''}`}><RadioGroupItem id={`answer-${q.id}-${o.id}`} value={o.id}/><span className="letter">{o.id}</span><div className="option-text"><span lang="en">{displayOptions[index]}</span>{showZh&&!activeExam&&visibleOptionZh(index)&&<p className="zh-text">{explainLegalText(visibleOptionZh(index))}</p>}</div>{graded&&q.explanation?.answer===o.id&&<Check size={17} className="text-[#2b876c] shrink-0 mt-1"/>}{graded&&!answer.correct&&answer.selected===o.id&&<XCircle size={17} className="text-[#b3495b] shrink-0 mt-1"/>}</label>)}</RadioGroup></div>
 <div className="sr-only" role="status" aria-live="polite">{graded&&`${answer.correct?'回答正确':answer.selected?'回答错误':'此题未作答'}，正确答案 ${q.explanation?.answer}`}</div>
 <div className="question-footer"><Button variant="ghost" disabled={position===0||busy||!!unsavedExam} onClick={()=>navigate(position-1)}><ChevronLeft size={16}/>上一题</Button><div>{!graded&&!activeExam&&session?.status!=='finished'&&<Button disabled={!selected||busy} onClick={submit}>{busy?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>}提交答案</Button>}{activeExam&&unsavedExam&&<Button disabled={busy} onClick={()=>choose(selected)}>重试保存</Button>}{activeExam&&position<ids.length-1&&<Button variant="ghost" disabled={busy||!!unsavedExam} onClick={()=>setDialog('finish')}>提前交卷</Button>}{position<ids.length-1?<Button variant={graded||activeExam?'default':'outline'} disabled={busy||!!unsavedExam} onClick={()=>navigate(position+1)}>下一题<ArrowRight size={16}/></Button>:session?.status==='finished'?<Button onClick={()=>setSummary(true)}>查看结果</Button>:<Button variant={graded||activeExam?'default':'outline'} disabled={busy||(!activeExam&&completed<ids.length)||!!unsavedExam} onClick={()=>activeExam?setDialog('finish'):finishSession()}>{activeExam?'交卷':'完成练习'}<Flag size={15}/></Button>}</div></div></article>{graded&&q.explanation&&<AnswerReview key={q.id} question={q} answer={answer} onOpenTextbook={ref=>setReader({questionId:q.id,bookId:ref.bookId,page:ref.pageNumbers[0]})}/>}</div>
 {readerOpen&&reader&&<TextbookReader key={q.id} references={linkedTextbooks(q.explanation?.textbookReferences)} books={textbookCatalog.books} initial={reader} onClose={()=>setReader(null)} sourceQuestionId={q.id} annotations={annotations}/>}</div><div className="bottom-caption">{data.questions.length} 道可练题目 · {sourceById(q.sourceId)?.name}{q.sourceId==='revise'?' · 原书解析 · 支持中英切换':q.sourceId==='qlts'?' · 中英对照 · 原题解析 · 未按现行法更新':' · 中文解析与考点回顾'}</div></>}
 {!loading&&view==='practice'&&data&&summary&&session&&<><div className="empty completion-summary"><div className="score-circle"><strong>{session.score??0}<span className="text-lg">/{ids.length}</span></strong><span>本次答对</span></div><h2>{session.score===ids.length?'这一组，全部答对。':'练习完成，继续巩固。'}</h2><p>{modeName(session.mode)} · 共 {ids.length} 题 · 正确率 {Math.round((session.score??0)/ids.length*100)}%<br/>{guest?'记录已保存在当前浏览器；清除网站数据或更换设备后不会保留。':'记录已保存；本组成绩不等同于完整考试水平。'}</p><section className="completion-overview" aria-labelledby="completion-overview-title"><div className="completion-overview-head"><h3 id="completion-overview-title">本次答题结果</h3><span>{session.score??0} 对 · {ids.length-(session.score??0)} 错误或未答</span></div><Progress value={ids.length?(session.score??0)/ids.length*100:0} aria-label="本次答题正确率" className="h-1.5 bg-[#e9edf6]"/><div className="completion-question-grid">{ids.map((id,i)=>{const result=session.answers[id];const state=result?.selected?(result.correct?'right':'wrong'):'';return <button key={id} className={`q-chip ${state}`} aria-label={`回顾第${i+1}题，${result?.selected?(result.correct?'答对':'答错'):'未答'}`} onClick={()=>{setSummary(false);void navigate(i);}}>{String(i+1).padStart(2,'0')}</button>;})}</div><div className="legend completion-legend"><span><i className="r"/>答对</span><span><i className="w"/>答错</span><span><i/>未答</span></div></section><div className="flex justify-center flex-wrap gap-3"><Button onClick={()=>{setSummary(false);void navigate(0);}} variant="outline"><BookOpen size={16}/>逐题回顾</Button>{pending.length>0&&<Button onClick={()=>start('wrong')} disabled={busy}><RotateCcw size={16}/>重练错题</Button>}<Button variant="outline" disabled={busy} onClick={()=>start('practice')}>再练一组</Button></div></div></>}
 {!loading&&view==='wrong'&&data&&<><div className="mistake-top"><Tabs value={showCorrected?'all':'pending'} onValueChange={v=>setShowCorrected(v==='all')}><TabsList><TabsTrigger value="pending">待巩固 {pending.length}</TabsTrigger><TabsTrigger value="all">全部错题 {data.mistakes.length}</TabsTrigger></TabsList></Tabs><Button disabled={!pending.length||busy} onClick={()=>start('wrong')}><RotateCcw size={15}/>开始重练</Button></div>{!mistakes.length?<div className="empty"><CheckCheck size={34}/><h2>{data.stats.answered?'暂时没有待巩固的错题':'你的错题会出现在这里'}</h2><p>{data.stats.answered?'重做答对的题目仍保留在“全部错题”中。':'先做几道题，答错的题目会自动收录。'}</p><Button onClick={()=>switchView('practice')}>回到练习<ArrowRight size={16}/></Button></div>:mistakes.map(m=>{const item=data.questions.find(q=>q.id===m.questionId)!;return <article className="mistake-item" key={m.questionId}><div className="flex justify-between items-center gap-3"><span className="tag">{sourceById(item.sourceId)?.name} · {questionNumberLabel(item)} · 错过 {m.wrongCount} 次</span><span className={`text-sm ${m.lastCorrect?'text-[#338b73]':'text-[#ae5060]'}`}>{m.lastCorrect?'已订正':'待巩固'}</span></div><h3>{m.topic}</h3><p>{normalizeInlineQuestionText(item.stem)}</p>{!m.lastCorrect&&<Button variant="outline" disabled={busy} onClick={()=>start('wrong',m.questionId)}>重做这道题<ArrowRight size={15}/></Button>}</article>;})}</>}
 {!loading&&view==='history'&&data&&<><StudyBreakdown data={data}/>{!data.sessions.length?<div className="empty"><History size={35}/><h2>从第一道题开始</h2><p>完成一次作答后，就可以在这里查看记录。</p><Button onClick={()=>switchView('practice')}>去练习</Button></div>:<div className="history-list">{data.sessions.map(s=><article className="history-row" key={s.id}><div className="flex items-center gap-4"><div className="stat-icon">{s.mode==='exam'?<Clock3/>:<BookOpen/>}</div><div><div className="history-title">{modeName(s.mode)} <span className="text-sm text-[#78869b] font-normal">· {subjectById(data.questions.find(q=>q.id===s.questionIds[0])?.subjectId)?.zh??'综合练习'}</span></div><p>{new Date(s.startedAt).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})} · {Object.values(s.answers).filter(a=>a.selected).length}/{s.questionIds.length} 题已作答 · {s.status==='finished'?'已完成':'进行中'}</p></div></div><div className="flex items-center gap-5"><div className="history-result">{s.mode==='exam'&&s.status==='active'?'—':`${s.score??0}/${s.questionIds.length}`}<small className="text-xs text-[#7b8ba2] block text-center">答对 / 总题数</small></div><Button disabled={busy} variant="outline" onClick={()=>openSession(s)}>{s.status==='finished'?'回顾':'继续'}<ChevronRight size={15}/></Button></div></article>)}</div>}<p className="bottom-caption">正确率只统计实际选择并提交答案的题目；重复作答按次数累计，尚未交卷的模拟考试不计入。</p></>}
 </div></main>
 <Dialog open={!!dialog} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="mode-dialog"><DialogHeader><DialogTitle>{dialog==='exam'?'开始限时练习':dialog==='practice'?'开始新的学习练习':'确认交卷？'}</DialogTitle><DialogDescription className="dialog-copy">{dialog==='exam'?`使用${sourceById(q?.sourceId??'sra')?.name}题组。答题时只显示英文，交卷后统一查看答案与解析。`:dialog==='practice'?'当前模拟考试的已保存答案会保留在学习记录中，计时不会暂停。新练习将逐题显示解析。':`已作答 ${completed} / ${ids.length} 题。${completed<ids.length?'未答题将计为错误。':''}交卷后不能修改本次答案，但可以另开一组重练。`}</DialogDescription></DialogHeader>{dialog==='exam'&&<><div className="mode-facts"><div><b>{examIds.length}</b><small>道题</small></div><div><b>{examMinutes} min</b><small>本组时长</small></div></div><p className="text-sm text-[#8d7644] leading-7">按每题1.8分钟计时，关闭网页后计时继续。</p></>}<DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>取消</Button><Button disabled={busy} onClick={()=>dialog==='finish'?finishSession():start(dialog==='exam'?'exam':'practice')}>{busy?'保存中…':dialog==='finish'?'确认交卷':'开始'}</Button></DialogFooter></DialogContent></Dialog>
 <VocabularySelection container={studyTextRef} question={q} enabled={focusedPractice&&!activeExam&&!wordDraft&&!sourceQuestion} onAdd={(word,example)=>setWordDraft(newWordDraft(q,session?.id,word,example))}/>
 <VocabularyEditor draft={wordDraft} onClose={()=>setWordDraft(null)} onChange={setWordDraft} controller={vocabulary} question={data?.questions.find(q=>q.id===wordDraft?.questionId)}/>
 <VocabularySource question={sourceQuestion} onClose={()=>setSourceQuestion(null)}/>
 <Toaster position="bottom-center" theme="light"/>
 </SidebarProvider>;
}
export default function StudyApp({authenticated,standalone=false}:{authenticated:boolean;standalone?:boolean}){return <StudyContent authenticated={authenticated} standalone={standalone}/>;}
