'use client';
import {useEffect,useRef,useState,useCallback,useMemo} from 'react';
import {BookOpen,NotebookPen,ChartNoAxesCombined,Check,CheckCheck,ChevronRight,ChevronLeft,ArrowRight,Languages,Clock3,HardDrive,Target,GraduationCap,TriangleAlert,ExternalLink,XCircle,X,Layers3,Loader2,Flag,Brain,ListChecks,LibraryBig,Settings2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Switch} from '@/components/ui/switch';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AnswerReview} from './answer-review';
import {CopyQuestionButton} from './copy-question-button';
import {CompletionSummary} from './completion-summary';
import {QuestionLibrary} from './question-library';
import {MistakeNotebook} from './mistake-notebook';
import {subjects} from '@/lib/subjects';
import {chapters} from '@/lib/chapters';
import {explainLegalText} from '@/lib/review-language';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Popover,PopoverContent,PopoverTrigger} from '@/components/ui/popover';
import {Progress} from '@/components/ui/progress';
import {Sidebar,SidebarProvider,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/ui/sidebar';
import type {Question,StudyData,Session} from '@/lib/study-types';
import {Toaster} from '@/components/ui/sonner';
import {useVocabulary,VocabularyPanel,VocabularyEditor,VocabularySelection,VocabularySource,newWordDraft,cardDraft} from './vocabulary-panel';
import {dueCards} from '@/lib/vocabulary';
import type {VocabularyDraft} from '@/lib/vocabulary';
import {TextbookLibrary} from './textbook-library';
import {useTextbookAnnotations} from './use-textbook-annotations';
import {useTextbookBookmarks} from './use-textbook-bookmarks';
import {useTextbookCatalog} from './use-textbook-catalog';
import {normalizeInlineQuestionText} from '@/lib/question-text';
import {systemQuestionNumber} from '@/lib/system-question-number';
import {applyGuestStudyAction} from '@/lib/guest-study';
import {getNextChapter,type PracticeScope} from '@/lib/next-chapter';
import {readWorkspace,hydrateWorkspace,writeWorkspace,workspaceKey,type WorkspaceSnapshot} from '@/lib/study-workspace';
const modeName=(m:string)=>m==='exam'?'历史练习':m==='wrong'?'错题重练':'刷题练习';
const elapsedTime=(seconds:number)=>{const hours=Math.floor(seconds/3600),minutes=Math.floor(seconds%3600/60),rest=seconds%60;return hours?`${String(hours).padStart(2,'0')}:${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`:`${String(minutes).padStart(2,'0')}:${String(rest).padStart(2,'0')}`;};
function QuestionTimer({onClose}:{onClose:()=>void}){const[seconds,setSeconds]=useState(0);useEffect(()=>{const startedAt=Date.now();const timer=window.setInterval(()=>setSeconds(Math.floor((Date.now()-startedAt)/1000)),1000);return()=>window.clearInterval(timer);},[]);const label=elapsedTime(seconds);return <div className="question-timer" role="timer" aria-label={`本题用时 ${label}`}><Clock3 size={16}/><span>{label}</span><button type="button" onClick={onClose} aria-label="关闭计时" title="关闭计时"><X size={14}/></button></div>;}
function QuestionProgress({ids,position,session,activeExam,busy,blocked,onNavigate}:{ids:string[];position:number;session:Session|null|undefined;activeExam:boolean;busy:boolean;blocked:boolean;onNavigate:(index:number)=>Promise<boolean>}){
 const[open,setOpen]=useState(false);
 const completed=ids.filter(id=>session?.answers[id]?.selected).length;
 return <Popover open={open} onOpenChange={setOpen}><PopoverTrigger asChild><Button variant="ghost" size="sm" aria-label={`打开答题进度，已作答 ${completed} / ${ids.length} 题`}><ListChecks size={16}/>答题进度</Button></PopoverTrigger><PopoverContent className="question-progress-popover" align="end" sideOffset={8}><div className="question-progress-head"><h2>答题进度</h2><span>{completed} / {ids.length} 已作答</span></div><Progress value={ids.length?completed/ids.length*100:0} aria-label={`已作答 ${completed} / ${ids.length} 题`} className="h-1.5 bg-[#e9edf6]"/><div className="question-grid" aria-label="题目列表">{ids.map((id,index)=>{const result=session?.answers[id];const state=result?.selected?(activeExam?'saved':result.correct===true?'right':result.correct===false?'wrong':'saved'):'';const stateLabel=result?.selected?(activeExam?'已作答':result.correct===true?'答对':result.correct===false?'答错':'已作答'):'未作答';return <button type="button" key={id} className={`q-chip ${state} ${index===position?'current':''}`} aria-current={index===position?'step':undefined} aria-label={`第 ${index+1} 题，系统题号 ${systemQuestionNumber(id)}，${stateLabel}${index===position?'，当前题':''}`} title={`系统题号：${systemQuestionNumber(id)}`} disabled={busy||blocked} onClick={()=>{setOpen(false);void onNavigate(index);}}>{String(index+1).padStart(2,'0')}</button>;})}</div><div className="legend question-progress-legend">{activeExam?<span><i className="saved"/>已答</span>:<><span><i className="r"/>答对</span><span><i className="w"/>答错</span></>}<span><i/>未答</span><span><i className="current"/>当前题</span></div></PopoverContent></Popover>;
}
function Nav({view,setView,due,guest,showLogin}:{view:string;setView:(v:string)=>void;due:number;guest:boolean;showLogin:boolean}){const {setOpenMobile}=useSidebar();return <Sidebar collapsible="offcanvas"><SidebarHeader className="p-0"><div className="brand"><div className="brand-mark">S</div><div><strong>SQE Practice</strong><small>个人刷题室</small></div></div></SidebarHeader><SidebarContent className="sidebar-menu-content"><div className="side-label">MY WORKSPACE</div><SidebarMenu className="side-nav">{[{id:'library',label:'题库分类',icon:Layers3},{id:'practice',label:'刷题练习',icon:BookOpen},{id:'materials',label:'教材笔记',icon:LibraryBig},{id:'wrong',label:'错题本',icon:NotebookPen},{id:'memory',label:'艾宾浩斯记忆',icon:Brain},{id:'history',label:'学习记录',icon:ChartNoAxesCombined},{id:'settings',label:'系统设置',icon:Settings2}].map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={view===n.id} onClick={()=>{setView(n.id);setOpenMobile(false);}}><n.icon/><span>{n.label}</span>{n.id==='memory'&&due>0&&<span className="ml-auto text-xs rounded bg-[#40577d] px-2 py-0.5">{due}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter className="p-0"><div className="side-footer"><div className="avatar">{guest?<HardDrive size={18}/>:<GraduationCap size={19}/>}</div><div className="text-sm">{guest?'访客学习空间':'我的学习空间'}<small>{guest?'当前浏览器 · 自动保存':'个人记录 · 云端同步'}</small>{showLogin&&<a className="sidebar-login" href="/signin-with-chatgpt?return_to=%2F" target="_top">登录同步</a>}</div></div></SidebarFooter></Sidebar>}
const accuracyText=(value:number|null)=>value==null?'—':`${value}%`;
function StudyBreakdown({data}:{data:StudyData}){
 const bySubject=new Map(data.stats.subjects.map(item=>[item.subjectId,item]));
 return <section className="history-breakdown" aria-label="科目与考点统计"><div className="subject-stat-list">{subjects.map(subject=>{const stat=bySubject.get(subject.id);const answered=stat?.answered??0;const correct=stat?.correct??0;const accuracy=stat?.accuracy??null;const subjectChapters=chapters.filter(chapter=>chapter.subjectId===subject.id);const byChapter=new Map(stat?.chapters.map(item=>[item.chapterId,item])??[]);const uncategorized=byChapter.get(null);return <details className="subject-stat-card" key={subject.id}><summary><div className="subject-stat-title"><span>{subject.id==='legal-services'?'FLK1 / FLK2':subject.group}</span><div><strong>{subject.zh}</strong><small>{subject.en}</small></div></div><div className="subject-stat-meter"><Progress value={accuracy??0} aria-label={`${subject.zh}正确率`} className="h-1.5 bg-[#e7ebf3]"/><small>{correct}/{answered} 题答对</small></div><div className="subject-stat-value"><strong>{answered}</strong><small>答题数量</small></div><div className="subject-stat-value accuracy"><strong>{accuracyText(accuracy)}</strong><small>正确率</small></div><ChevronRight className="subject-stat-chevron" size={18}/></summary><div className="chapter-stat-wrap">{subjectChapters.length||uncategorized?<table className="chapter-stat-table"><thead><tr><th>专题 / 章节</th><th>答题数量</th><th>正确率</th></tr></thead><tbody>{subjectChapters.map(chapter=>{const chapterStat=byChapter.get(chapter.id);return <tr key={chapter.id}><td><b>{chapter.kind==='syllabus'?`专题 ${chapter.number}`:`第 ${chapter.number} 章`}</b><span>{chapter.zh}</span></td><td>{chapterStat?.answered??0}</td><td><strong>{accuracyText(chapterStat?.accuracy??null)}</strong><small>{chapterStat?.answered?`${chapterStat.correct}/${chapterStat.answered} 题答对`:'暂无作答'}</small></td></tr>;})}{uncategorized&&<tr><td><b>其他</b><span>尚未匹配主章节的题目</span></td><td>{uncategorized.answered}</td><td><strong>{accuracyText(uncategorized.accuracy)}</strong><small>{uncategorized.correct}/{uncategorized.answered} 题答对</small></td></tr>}</tbody></table>:<p className="chapter-stat-empty">该科目暂无章节目录。</p>}</div></details>;})}</div></section>;
}
const GUEST_STUDY_KEY='sqe-practice:guest-study:v1';
const REVIEW_NAVIGATION_KEY='sqe-practice:review-navigation:v1';
function readGuestStudy(){try{return JSON.parse(localStorage.getItem(GUEST_STUDY_KEY)??'null');}catch{return null;}}
function saveGuestStudy(state:unknown){try{localStorage.setItem(GUEST_STUDY_KEY,JSON.stringify(state));}catch{throw new Error('浏览器无法保存学习进度，请检查是否允许本站使用本机存储。');}}
function StudyContent({authenticated,standalone}:{authenticated:boolean;standalone:boolean}){
 const guest=standalone||!authenticated;
 const vocabulary=useVocabulary(guest);
 const annotations=useTextbookAnnotations(guest);
 const bookmarks=useTextbookBookmarks(guest);
 const textbookCatalog=useTextbookCatalog(guest);
 const[wordDraft,setWordDraft]=useState<VocabularyDraft|null>(null),[sourceQuestion,setSourceQuestion]=useState<Question|null>(null);
 const studyTextRef=useRef<HTMLDivElement|null>(null);
 const[workspaceReady,setWorkspaceReady]=useState(false);
 const[practiceScopes,setPracticeScopes]=useState<Record<string,PracticeScope>>({});

 const[data,setData]=useState<StudyData|null>(null);const[view,setView]=useState('library');const[loading,setLoading]=useState(true);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[needsLogin,setNeedsLogin]=useState(false);const[selected,setSelected]=useState('');const[showZh,setShowZh]=useState(false);const[dialog,setDialog]=useState<'finish'|null>(null);const[summary,setSummary]=useState(false);const[localPosition,setLocalPosition]=useState(0);const[questionTimerVisible,setQuestionTimerVisible]=useState(true);const[showReviewNavigation,setShowReviewNavigation]=useState(()=>{try{return typeof window==='undefined'||window.localStorage.getItem(REVIEW_NAVIGATION_KEY)!=='false';}catch{return true;}});const[preferenceError,setPreferenceError]=useState('');
 function updateReviewNavigation(visible:boolean){setShowReviewNavigation(visible);try{window.localStorage.setItem(REVIEW_NAVIGATION_KEY,String(visible));setPreferenceError('');}catch{setPreferenceError('设置已在当前页面生效，但浏览器未能保存；刷新后可能恢复默认。');}}
 const busyRef=useRef(false);const dataRef=useRef(data);dataRef.current=data;const selectedRef=useRef(selected);selectedRef.current=selected;const opRef=useRef<(body:Record<string,unknown>)=>Promise<StudyData|undefined>>(null);const webActions=useRef<Record<string,(x:any)=>any>>({});
 const session=data?.session;const ids=session?.questionIds??data?.questions.filter(q=>q.sourceId==='sra').map(q=>q.id)??[];const position=session?.position??localPosition;const q=data?.questions.find(q=>q.id===ids[position]);const answer=q?session?.answers[q.id]:undefined;const graded=!!answer&&(session?.mode!=='exam'||session.status==='finished');const activeExam=session?.mode==='exam'&&session.status==='active';const completed=ids.filter(id=>session?.answers[id]?.selected).length;
 const questionStats=q?data?.questionStats?.[q.id]:undefined;
 const displayStem=normalizeInlineQuestionText(q?.stem??'');
 const displayAsk=normalizeInlineQuestionText(q?.ask??'');
 const displayOptions=useMemo(()=>q?.options.map(option=>normalizeInlineQuestionText(option.en))??[],[q]);
 const visibleStemZh=normalizeInlineQuestionText(q?.stemZh||'');
 const visibleAskZh=normalizeInlineQuestionText(q?.askZh||'');
 const visibleOptionZh=(index:number)=>normalizeInlineQuestionText(q?.options[index]?.zh||'');
 const hasQuestionTranslation=!!visibleStemZh||!!visibleAskZh||!!q?.options.some(option=>option.zh?.trim());
 useEffect(()=>{window.scrollTo({top:0});},[view,q?.id,session?.id,summary]);
 const adopt=useCallback((d:StudyData)=>{setData(d);const id=d.session?.questionIds[d.session.position]??d.questions.filter(q=>q.sourceId==='sra')[localPosition]?.id;setSelected(id?d.session?.answers[id]?.selected??'':'');},[localPosition]);
 async function request(body?:Record<string,unknown>,sessionId?:string){
  if(guest){
   const action={...body,action:body?.action??'hydrate',sessionId:body?.sessionId??sessionId};
   if(standalone){const value=applyGuestStudyAction(readGuestStudy(),action);saveGuestStudy(value.state);setNeedsLogin(false);return value.data;}
   const response=await fetch('/api/guest-study',{method:'POST',headers:{'Content-Type':'application/json','X-Study-Action':'1'},body:JSON.stringify({...action,state:readGuestStudy()})});const value=await response.json() as {data?:StudyData;state?:unknown;error?:string};if(!response.ok||!value.data)throw new Error(value.error??'暂时无法读取本机进度，请重试。');saveGuestStudy(value.state);setNeedsLogin(false);return value.data;
  }
  const response=await fetch('/api/study'+(sessionId?'?session='+encodeURIComponent(sessionId):''),body?{method:'POST',headers:{'Content-Type':'application/json','X-Study-Action':'1'},body:JSON.stringify(body)}:{cache:'no-store'});const value=await response.json() as StudyData & {error?:string};if(!response.ok){if(response.status===401)setNeedsLogin(true);throw new Error(value.error??'暂时无法连接，请重试。');}setNeedsLogin(false);return value as StudyData;
 }
 const load=useCallback(async()=>{
  setLoading(true);setError('');setWorkspaceReady(false);
  let saved:WorkspaceSnapshot|null=null;
  try{saved=readWorkspace(window.sessionStorage,workspaceKey(guest));}catch{}
  try{
   const {data:d,workspace:restored}=await hydrateWorkspace(saved,id=>request(undefined,id));
   setData(d);setView(restored.view);setSummary(restored.summary);setLocalPosition(restored.localPosition);setSelected(restored.selected);setShowZh(restored.showZh);setPracticeScopes(restored.scopes);setWorkspaceReady(true);
  }catch(e){setError((e as Error).message);}finally{setLoading(false);}
 },[]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{
  if(!workspaceReady||loading||!data)return;
  const scopes=Object.fromEntries(Object.entries(practiceScopes).filter(([id])=>data.sessions.some(item=>item.id===id)));
  const saved:WorkspaceSnapshot={version:1,view:view as WorkspaceSnapshot['view'],sessionId:session?.id??null,sessionStatus:session?.status??null,summary,localPosition,showZh,selection:q?{questionId:q.id,value:selected}:null,scopes};
  try{writeWorkspace(window.sessionStorage,workspaceKey(guest),saved);}catch{}
 },[workspaceReady,loading,data,guest,view,session,summary,localPosition,showZh,selected,q?.id,practiceScopes]);
 const mutate=useCallback(async(body:Record<string,unknown>)=>{if(busyRef.current)return;busyRef.current=true;setBusy(true);setError('');try{const d=await request(body);adopt(d);return d;}catch(e){setError((e as Error).message);return undefined;}finally{busyRef.current=false;setBusy(false);}},[adopt]);opRef.current=mutate;
 async function start(mode:'practice'|'wrong',questionId?:string,subjectId?:string,sourceId?:string,chapterId?:string,sourceSet?:string){
  const actualSource=sourceId==='all'?undefined:sourceId??(mode==='wrong'?undefined:q?.sourceId??'sra');
  const actualSourceSet=sourceSet??(mode!=='wrong'&&sourceId===undefined&&subjectId===undefined&&chapterId===undefined?activeSourceSet:undefined);
  const d=await mutate({action:'start',id:crypto.randomUUID(),mode,questionId,subjectId,chapterId,sourceSet:actualSourceSet,sourceId:actualSource});
  if(d){if(d.session)setPracticeScopes(value=>({...value,[d.session!.id]:{subjectId,sourceId:actualSource??'all',chapterId,sourceSet:actualSourceSet}}));setView('practice');setSummary(false);setDialog(null);setShowZh(false);}return d;
 }
 async function navigate(next:number){if(next<0||next>=ids.length||busyRef.current)return false;if(session){const d=await mutate({action:'navigate',sessionId:session.id,position:next});if(!d)return false;}else{setLocalPosition(next);setSelected('');}setShowZh(false);setSummary(false);return true;}
 async function submit(){if(!q||!selected||busyRef.current||graded)return;let s=session;const choice=selected;if(!s){const d=await start('practice');if(!d?.session)return;s=d.session;if(position!==0){const moved=await mutate({action:'navigate',sessionId:s.id,position});if(!moved)return;}}const d=await mutate({action:'answer',sessionId:s.id,questionId:q.id,selected:choice});if(d){if(d.session?.mode==='exam'&&d.session.status==='finished')setSummary(true);}}
 async function choose(value:string){if(busyRef.current||graded)return;setSelected(value);if(activeExam&&q){const d=await mutate({action:'answer',sessionId:session.id,questionId:q.id,selected:value});if(d?.session?.status==='finished')setSummary(true);}}
 async function finishSession(){if(!session)return;const d=await mutate({action:'finish',sessionId:session.id});if(d){setDialog(null);setSummary(true);}}
 function toggleQuestionLanguage(){setShowZh(value=>!value);}
 async function openSession(s:Session){if(busyRef.current)return;if(s.id===session?.id&&session.mode!=='exam'){setView('practice');setSummary(session.status==='finished');return;}busyRef.current=true;setBusy(true);setError('');try{const d=await request(undefined,s.id);adopt(d);setView('practice');setSummary(d.session?.status==='finished');setShowZh(false);}catch(e){setError((e as Error).message);}finally{busyRef.current=false;setBusy(false);}}
 const unsavedExam=activeExam&&selected!==(answer?.selected??'');
 webActions.current={read:()=>({view,mode:session?.mode??'practice',question:q?{id:q.id,systemNumber:systemQuestionNumber(q.id),number:q.number,stem:q.stem,ask:q.ask,options:q.options}:null,selected,submitted:graded,stats:data?.stats}),navigate:async(input:unknown)=>{const n=(input as {questionNumber?:number})?.questionNumber;if(!Number.isInteger(n)||!n||n<1||n>ids.length)throw Error('Invalid questionNumber');if(unsavedExam)throw Error('Save the pending exam answer first');const index=n-1;if(!await navigate(index))throw Error('Unable to navigate');return{questionNumber:n};}};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const registrations=[{name:'read_current_sqe_question',description:'Read the visible practice question, staged selection and study statistics without showing an unsubmitted answer.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:(input:unknown)=>{if(input&&Object.keys(input as object).length)throw Error('No arguments accepted');return webActions.current.read(input);}},{name:'navigate_to_sqe_question',description:'Navigate to a numbered question in the current practice session and save its position. Does not submit an answer.',inputSchema:{type:'object',properties:{questionNumber:{type:'integer',minimum:1}},required:['questionNumber'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>webActions.current.navigate(input)}];for(const t of registrations){try{void Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{});}catch{}}return()=>lifecycle.abort();},[]);
 const switchView=(v:string)=>{setView(v);setSummary(false);};
 const pending=data?.mistakes.filter(m=>!m.lastCorrect)??[];
 const activeSourceSet=q?.sourceSet&&session?.questionIds.every(id=>data?.questions.find(item=>item.id===id)?.sourceSet===q.sourceSet)?q.sourceSet:undefined;
 const nextChapter=data&&session?getNextChapter(session,data.questions,practiceScopes[session.id]):null;
 const focusedPractice=view==='practice'&&!summary;
 const previousQuestionButton=<Button variant="ghost" disabled={position===0||busy||!!unsavedExam} onClick={()=>navigate(position-1)}><ChevronLeft size={16}/>上一题</Button>;
 const nextQuestionButton=position<ids.length-1?<Button variant={graded||activeExam?'default':'outline'} disabled={busy||!!unsavedExam} onClick={()=>navigate(position+1)}>下一题<ArrowRight size={16}/></Button>:session?.status==='finished'?<Button onClick={()=>setSummary(true)}>查看结果</Button>:<Button variant={graded||activeExam?'default':'outline'} disabled={busy||(!activeExam&&completed<ids.length)||!!unsavedExam} onClick={()=>activeExam?setDialog('finish'):finishSession()}>{activeExam?'交卷':'完成练习'}<Flag size={15}/></Button>;
 const title=view==='memory'?'艾宾浩斯记忆':view==='materials'?'教材笔记':view==='library'?'题库分类':view==='wrong'?'错题本':view==='history'?'学习记录':view==='settings'?'系统设置':summary?'本次练习完成':session?.mode==='wrong'?'错题重练':'刷题练习';
 return <SidebarProvider style={{'--sidebar-width':'224px'} as React.CSSProperties}><Nav view={view} setView={switchView} due={vocabulary.data?dueCards(vocabulary.data.cards,vocabulary.data.today).length:0} guest={guest} showLogin={guest&&!standalone}/><main className="min-w-0 flex-1"><SidebarTrigger className="mobile-sidebar-trigger" aria-label="打开导航菜单" title="打开导航菜单"/><div className={`workspace ${focusedPractice?'practice-workspace':''} ${view==='library'?'library-workspace':''} ${view==='memory'?'memory-workspace':''} ${view==='materials'?'textbook-library-workspace':''}`}>{view!=='practice'&&view!=='library'&&view!=='memory'&&view!=='materials'&&<><div className="page-heading"><div><h1>{title}</h1></div></div>
 {view!=='settings'&&<div className="stat-strip"><div className="stat"><div className="stat-icon"><CheckCheck/></div><div><small>累计作答</small><strong>{data?.stats.answered??0}</strong><em>次</em></div></div><div className="stat"><div className="stat-icon"><Target/></div><div><small>累计正确率</small><strong>{data?.stats.accuracy==null?'—':`${data.stats.accuracy}%`}</strong></div></div><div className="stat"><div className="stat-icon"><NotebookPen/></div><div><small>错题</small><strong>{data?.stats.wrongCount??0}</strong><em>题</em></div></div></div>}</>}
 {error&&<div className="notice error" role="alert"><TriangleAlert size={18} className="shrink-0 mt-0.5"/><div className="flex-1">{error}{unsavedExam&&<p className="mt-1">当前选择尚未确认保存，请点击“重试保存”。</p>}</div>{needsLogin?<a href="/signin-with-chatgpt?return_to=%2F" target="_top" className="underline whitespace-nowrap">登录</a>:!data?<Button variant="outline" onClick={load}>重试</Button>:unsavedExam?<Button variant="outline" onClick={()=>choose(selected)}>重试保存</Button>:<Button variant="ghost" onClick={()=>setError('')}>关闭</Button>}</div>}
 {loading&&<div className="empty"><Loader2 size={27} className="animate-spin"/><h2>正在读取你的学习进度</h2><p>准备好后，就可以开始答题。</p></div>}
 {view==='settings'&&<section className="settings-panel" aria-labelledby="practice-settings-title"><h2 id="practice-settings-title">刷题页面</h2><div className="settings-row"><div><label htmlFor="review-navigation-switch">显示解析下方的上一题、下一题</label><p id="review-navigation-description">答题后，在答案解析下方显示第二组题目导航按钮。</p></div><Switch id="review-navigation-switch" checked={showReviewNavigation} onCheckedChange={updateReviewNavigation} aria-describedby="review-navigation-description"/></div>{preferenceError&&<p className="settings-error" role="alert">{preferenceError}</p>}</section>}
 {view==='memory'&&<VocabularyPanel controller={vocabulary} onAdd={()=>setWordDraft(newWordDraft())} onEdit={card=>setWordDraft(cardDraft(card))} onSource={id=>setSourceQuestion(data?.questions.find(q=>q.id===id)??null)} onPractice={()=>switchView('practice')} activeExam={!!activeExam}/>}
 {view==='materials'&&<TextbookLibrary controller={annotations} bookmarks={bookmarks} catalog={textbookCatalog} guest={guest}/>}
 {!loading&&view==='library'&&data&&<QuestionLibrary data={data} busy={busy} onStart={(id,sourceId,chapterId,sourceSet)=>void start('practice',undefined,id,sourceId,chapterId,sourceSet)} onResume={s=>void openSession(s)}/>}
 {!loading&&view==='practice'&&data&&q&&!summary&&<><div className="study-grid practice-single"><div className="study-main" ref={studyTextRef} onClickCapture={event=>{if((event.target as HTMLElement).closest('label.option')&&window.getSelection()?.toString().trim()){event.preventDefault();event.stopPropagation();}}}><article id="current-question" className="question-card"><div className="question-top"><h1 className="question-number"><span className="sr-only">第 </span><b>{String(position+1).padStart(2,'0')}</b><span className="sr-only"> 题</span> / {String(ids.length).padStart(2,'0')}<span className="question-system-number">系统题号：{systemQuestionNumber(q.id)}</span></h1><div className="question-controls"><CopyQuestionButton key={`${session?.id??'preview'}:${q.id}`} question={q} selected={selected} includeAnswer={graded&&!activeExam} disabled={busy}/><QuestionProgress ids={ids} position={position} session={session} activeExam={!!activeExam} busy={busy} blocked={!!unsavedExam} onNavigate={navigate}/>{questionTimerVisible?<QuestionTimer key={q.id} onClose={()=>setQuestionTimerVisible(false)}/>:<Button className="timer-toggle" variant="ghost" size="sm" onClick={()=>setQuestionTimerVisible(true)}><Clock3 size={16}/>开启计时</Button>}{!activeExam&&hasQuestionTranslation&&<Button variant="ghost" size="sm" aria-pressed={showZh} onClick={toggleQuestionLanguage}><Languages size={16}/> {showZh?'隐藏中文':'显示中文'}</Button>}</div></div><div className="question-body"><p className="question-stem" lang="en">{displayStem}</p>{showZh&&!activeExam&&visibleStemZh&&<p className="zh-text stem-zh">{explainLegalText(visibleStemZh)}</p>}<p className="question-ask" lang="en">{displayAsk}</p>{showZh&&!activeExam&&visibleAskZh&&<p className="zh-text mb-4">{explainLegalText(visibleAskZh)}</p>}<RadioGroup aria-label="请选择一个最佳答案" value={selected} onValueChange={choose} disabled={graded||busy||session?.status==='finished'} className="options">{q.options.map((o,index)=><label key={o.id} htmlFor={`answer-${q.id}-${o.id}`} className={`option ${selected===o.id?'selected':''} ${graded&&q.explanation?.answer===o.id?'correct':''} ${graded&&answer.selected===o.id&&!answer.correct?'incorrect':''}`}><RadioGroupItem id={`answer-${q.id}-${o.id}`} value={o.id}/><span className="letter">{o.id}</span><div className="option-text"><span lang="en">{displayOptions[index]}</span>{showZh&&!activeExam&&visibleOptionZh(index)&&<p className="zh-text">{explainLegalText(visibleOptionZh(index))}</p>}</div>{graded&&q.explanation?.answer===o.id&&<Check size={17} className="text-[#2b876c] shrink-0 mt-1"/>}{graded&&!answer.correct&&answer.selected===o.id&&<XCircle size={17} className="text-[#b3495b] shrink-0 mt-1"/>}</label>)}</RadioGroup></div>
 <div className="sr-only" role="status" aria-live="polite">{graded&&`${answer.correct?'回答正确':answer.selected?'回答错误':'此题未作答'}，正确答案 ${q.explanation?.answer}`}</div>
 <div className="question-footer">{previousQuestionButton}<div>{!graded&&!activeExam&&session?.status!=='finished'&&<Button disabled={!selected||busy} onClick={submit}>{busy?<Loader2 size={15} className="animate-spin"/>:<Check size={15}/>}提交答案</Button>}{activeExam&&unsavedExam&&<Button disabled={busy} onClick={()=>choose(selected)}>重试保存</Button>}{activeExam&&position<ids.length-1&&<Button variant="ghost" disabled={busy||!!unsavedExam} onClick={()=>setDialog('finish')}>提前交卷</Button>}{nextQuestionButton}</div></div></article>{graded&&q.explanation&&<><AnswerReview key={q.id} question={q} answer={answer}/>{showReviewNavigation&&<nav className="review-navigation" aria-label="解析后的题目导航">{previousQuestionButton}{nextQuestionButton}</nav>}</>}<div className="question-answer-counts" role="status" aria-live="polite" aria-atomic="true"><span>本题累计</span><span>答对 <b>{questionStats?.correct??0}</b> 次</span><span>答错 <b>{questionStats?.wrong??0}</b> 次</span></div></div>
 </div></>}
 {!loading&&view==='practice'&&data&&summary&&session&&<CompletionSummary session={session} label={modeName(session.mode)} busy={busy} hasPendingMistakes={pending.length>0} onNavigate={index=>{void navigate(index);}} onRetry={()=>{void start('wrong');}} nextChapterAvailable={!!nextChapter} nextChapterTitle={nextChapter?.chapter.zh} onNextChapter={()=>{if(nextChapter)void start('practice',undefined,nextChapter.subjectId,nextChapter.sourceId,nextChapter.chapterId,nextChapter.sourceSet);else switchView('library');}}/>}
 {!loading&&view==='wrong'&&data&&<MistakeNotebook data={data} busy={busy} onRetry={(questionId,subjectId)=>void start('wrong',questionId,subjectId)} onPractice={()=>switchView('practice')}/>}
 {!loading&&view==='history'&&data&&<><StudyBreakdown data={data}/><p className="bottom-caption">正确率只统计实际选择并提交答案的题目；重复作答按次数累计。</p></>}
 </div></main>
 <Dialog open={dialog==='finish'} onOpenChange={open=>{if(!open)setDialog(null);}}><DialogContent className="mode-dialog"><DialogHeader><DialogTitle>确认完成这组练习？</DialogTitle><DialogDescription className="dialog-copy">已作答 {completed} / {ids.length} 题。{completed<ids.length?'未答题将计为错误。':''}完成后不能修改本次答案，但可以另开一组重练。</DialogDescription></DialogHeader><DialogFooter><Button variant="outline" onClick={()=>setDialog(null)}>取消</Button><Button disabled={busy} onClick={finishSession}>{busy?'保存中…':'确认完成'}</Button></DialogFooter></DialogContent></Dialog>
 <VocabularySelection container={studyTextRef} question={q} enabled={focusedPractice&&!activeExam&&!wordDraft&&!sourceQuestion} onAdd={(word,example)=>setWordDraft(newWordDraft(q,session?.id,word,example))}/>
 <VocabularyEditor draft={wordDraft} onClose={()=>setWordDraft(null)} onChange={setWordDraft} controller={vocabulary} question={data?.questions.find(q=>q.id===wordDraft?.questionId)}/>
 <VocabularySource question={sourceQuestion} onClose={()=>setSourceQuestion(null)}/>
 <Toaster position="bottom-center" theme="light"/>
 </SidebarProvider>;
}
export default function StudyApp({authenticated,standalone=false}:{authenticated:boolean;standalone?:boolean}){return <StudyContent authenticated={authenticated} standalone={standalone}/>;}
