import { sqliteTable,text,integer,index,primaryKey,uniqueIndex } from 'drizzle-orm/sqlite-core';
export const sessions=sqliteTable('sessions',{id:text('id').primaryKey(),userId:text('user_id').notNull(),mode:text('mode').notNull(),status:text('status').notNull().default('active'),questionIds:text('question_ids').notNull(),position:integer('position').notNull().default(0),startedAt:integer('started_at').notNull(),finishedAt:integer('finished_at')},t=>[index('idx_sessions_user_started').on(t.userId,t.startedAt)]);
export const responses=sqliteTable('responses',{sessionId:text('session_id').notNull().references(()=>sessions.id),questionId:text('question_id').notNull(),selected:text('selected').notNull(),correct:integer('correct').notNull().default(0),answeredAt:integer('answered_at').notNull()},t=>[primaryKey({columns:[t.sessionId,t.questionId]})]);
export const vocabulary=sqliteTable('vocabulary',{
 id:text('id').primaryKey(),userId:text('user_id').notNull(),word:text('word').notNull(),wordKey:text('word_key').notNull(),kind:text('kind').notNull().default('term'),meaning:text('meaning').notNull().default(''),example:text('example').notNull().default(''),questionId:text('question_id'),sessionId:text('session_id'),subjectId:text('subject_id'),sourceLabel:text('source_label').notNull().default(''),stage:integer('stage').notNull().default(0),nextReview:text('next_review').notNull(),reviewCount:integer('review_count').notNull().default(0),lastReviewedAt:integer('last_reviewed_at'),lastReviewedDate:text('last_reviewed_date'),queueDate:text('queue_date'),queueOrder:integer('queue_order').notNull().default(0),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(0)
},t=>[uniqueIndex('idx_vocabulary_user_word').on(t.userId,t.wordKey),index('idx_vocabulary_user_due').on(t.userId,t.nextReview)]);
export const textbookAnnotations=sqliteTable('textbook_annotations',{
 id:text('id').primaryKey(),userId:text('user_id').notNull(),bookId:text('book_id').notNull(),page:integer('page').notNull(),quote:text('quote').notNull(),note:text('note').notNull().default(''),color:text('color').notNull().default('yellow'),rects:text('rects').notNull(),sourceQuestionId:text('source_question_id'),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(0)
},t=>[index('idx_textbook_annotations_user_book_page').on(t.userId,t.bookId,t.page),index('idx_textbook_annotations_user_updated').on(t.userId,t.updatedAt)]);
export const textbookTitles=sqliteTable('textbook_titles',{
 userId:text('user_id').notNull(),bookId:text('book_id').notNull(),title:text('title').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(0)
},t=>[primaryKey({columns:[t.userId,t.bookId]})]);
export const userTextbooks=sqliteTable('user_textbooks',{
 id:text('id').primaryKey(),userId:text('user_id').notNull(),title:text('title').notNull(),originalName:text('original_name').notNull(),pageCount:integer('page_count').notNull(),storageKey:text('storage_key').notNull(),sizeBytes:integer('size_bytes').notNull(),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(0)
},t=>[index('idx_user_textbooks_user_created').on(t.userId,t.createdAt)]);
export const textbookBookmarks=sqliteTable('textbook_bookmarks',{
 userId:text('user_id').notNull(),bookId:text('book_id').notNull(),page:integer('page').notNull(),note:text('note').notNull().default(''),createdAt:integer('created_at').notNull(),updatedAt:integer('updated_at').notNull(),revision:integer('revision').notNull().default(0)
},t=>[primaryKey({columns:[t.userId,t.bookId,t.page]}),index('idx_textbook_bookmarks_user_updated').on(t.userId,t.updatedAt)]);
